_push = $(eval _save$1 := $(MAKEFILE_LIST))
_pop = $(eval MAKEFILE_LIST := $(_save$1))
_INCLUDE = $(call _push,$1)$(eval include $(_ROOT)/$1/Makefile)$(call _pop,$1)
depends_on = $(call _INCLUDE,$1)
depends_on_no_build = $(eval _NO_RULES := T)$(call _INCLUDE,$1)$(eval _NO_RULES :=)
